### ISSUE TITLE
Logo design contribution

### ISSUE THREAD

**Issue by saifulfrank** [mahbubiftekhar/quickSMS#51]
Hi
I want to make a logo for this projects if you have any requirements then let me know.its totally free for open source projects.

**Comment by mahbubiftekhar** [comment]
Hi. Thanks for your images. Myself and Alex really like the second image, but can you make the corners rounded the same as the first image. We would also require the launcher icon in different sizes as per this link: http://iconhandbook.co.uk/reference/chart/android/

Also how would you like to be credited for your work? I can do this In the app's about page & on the Github README linking to your GitHub profile or website. 

Thanks

**Comment by saifulfrank** [comment]
great! check it now
![hdpi](https://user-images.githubusercontent.com/37498811/40729556-735b7308-644e-11e8-9fb4-e6e0dc9599dc.png)
![mdpi](https://user-images.githubusercontent.com/37498811/40729559-739c60b6-644e-11e8-84d4-64d56b63d31d.png)
![play_store](https://user-images.githubusercontent.com/37498811/40729560-73da9520-644e-11e8-8707-0cada1bbb098.png)
![xhdpi](https://user-images.githubusercontent.com/37498811/40729562-742c38c6-644e-11e8-938a-d104e50574d4.png)
![xxhdpi](https://user-images.githubusercontent.com/37498811/40729563-74691098-644e-11e8-9994-ebf041dd486d.png)
![xxxhdpi](https://user-images.githubusercontent.com/37498811/40729564-74a5437e-644e-11e8-8e08-bb176a94c4d4.png)
here is all launcher icon.

can I open a pull request for using this in app? I will also give you google drive link of all launcher icon size and editable source file

**Comment by saifulfrank** [comment]
please check pull #61 and merged it.
thank you

**Comment by mahbubiftekhar** [comment]
Thank you for your contribution. I have accepted your pull request and merged it. I will credit you in the readme as well.
