### ISSUE TITLE
Consolidate duplicated code in BaseActivity

### ISSUE THREAD

**Issue by Alex-Shand** [mahbubiftekhar/quickSMS#59]
Some examples, the same routine for wiping the app is in MainActivity and FallbackActivity. MainActivity and TextMessageActivity both have the same logic for choosing text colour depending on background colour.

**Comment by mahbubiftekhar** [comment]
This issue has been resolved, I have placed the offending code in BaseActivity to reduce duplication for both instances. Update with this will be pushed to the play store soon.
