### ISSUE TITLE
Suggestion to add a license

### ISSUE THREAD

**Issue by saifulfrank** [mahbubiftekhar/quickSMS#70]
Can you add a license to your project please? Then it will look better and perfect.
thank you

**Comment by mahbubiftekhar** [comment]
Hi. I have added the license to the README. Thanks

**Comment by saifulfrank** [comment]
hi, I was asked to add a license on your code list. is it possible to add a license.
thank you 😊

**Comment by mahbubiftekhar** [comment]
Hi. Sorry their seems to have been some confusion. I'm not sure what you mean by the code list? I'm happy to add it, but I'm just unsure where it needs to be. Thanks

**Comment by mahbubiftekhar** [comment]
@saifulfrank 
Hi. Sorry their seems to have been some confusion. I'm not sure what you mean by the code list? I'm happy to add it, but I'm just unsure where it needs to be added. Thanks

**Comment by saifulfrank** [comment]
![img_20180602_085419](https://user-images.githubusercontent.com/37498811/40869790-b23b0c0a-6642-11e8-9b34-8f1026f2ca16.png)
![screenshot_2018-06-02-08-53-21](https://user-images.githubusercontent.com/37498811/40869795-c24bf0c8-6642-11e8-9b3e-17271fa7d041.png)


I was askwd for something like that. Is that possible?

**Comment by saifulfrank** [comment]
Its very easy

**Comment by saifulfrank** [comment]
please check pull #72
