### ISSUE TITLE
Frequently Asked Question (FAQ) Proposal 

### ISSUE THREAD

**Issue by olayhemy** [mahbubiftekhar/quickSMS#78]
Hello there, I'd like to contribute to your awesome project by writing a Frequent Asked Questions (FAQ) for users self-service. Would love to hear from you, thanks

**Comment by mahbubiftekhar** [comment]
Hi. Thanks for your message and offer for contribution. Am I correct in saying you would like create and  add more FAQ's to the existing android activity? Thanks

**Comment by mahbubiftekhar** [comment]
Hello. I am closing this issue due to not getting a response. Of course you are more than welcome to open a new issue or contact me directly. You will find my business contact information on my website https://www.mahbubiftekhar.co.uk . 
Thanks
